openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample
paths:
  /without-additional-properties:
    delete:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /with-additional-properties-true:
    delete:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /with-additional-properties-false:
    delete:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
